export * from './Layouts';
export * from './UI';
export * from './Modals';
export * from './HOC';
export * from './CartPage';
export * from './Product';
export * from './Review';
export * from './Sliders';
export * from './CarColorPage';
export { NewSlider } from './Home/NewSlider';
export { LoginForm } from './LoginForm';
export { SendMailAgain } from './SendMailAgain';
export { ChangePasswordForm } from './ChangePasswordForm';
export { AuthError } from './AuthError';
export { StickyLinks } from './StickyLinks';
